server:
  port: 8001

mybatis:
  #配置别名,pojo的包名
  type-aliases-package: com.ping.pojo
  #mapper.xml文件的路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #mybatis核心配置文件
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
    #数据库相关
  datasource:
    #url和driverclassname是8.0以上版本的写法,新增最后的时区
    url: jdbc:mysql://127.0.0.1:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pxj1214
    #程序运行的时候执行sql
    #initialization-mode: always
    #修改数据库连接池为druid
    type: com.alibaba.druid.pool.DruidDataSource


