server:
  port: 8002

mybatis:
  #配置别名,pojo的包名
  type-aliases-package: com.ping.pojo
  #mapper.xml文件的路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #mybatis核心配置文件
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept #eureka上的实例左边名称,三个服务名称一致
    #数据库相关
  datasource:
    #url和driverclassname是8.0以上版本的写法,新增最后的时区
    url: jdbc:mysql://192.168.10.130:3306/db02?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pxj1214
    #程序运行的时候执行sql
    #initialization-mode: always
    #修改数据库连接池为druid
    type: com.alibaba.druid.pool.DruidDataSource

#Eureka配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 #x修改eureka上的默认描述信息！（实例右侧名称）

#info配置
info:
  app.name: ping-springcloud
  company.name: blog.ping.study.com




